### ISSUE TITLE
run application

### ISSUE THREAD

**Issue by haithamRD** [rishabh-karmakar/Facial-Recognition-Based-Attendance-System#2]
hey sir, 
i have so problem to run this application about  tkinter if you can send to me the source code used in your video on youtube 
thnx sir

**Comment by rishabh-karmakar** [comment]
The thing is, while authenticate is running, it needs to be linked to the other screen.py modules. But in doing so, it preloads all the libraries such as tensorflow in Add_new.py and recog.py. And hence would take much time to get loaded.
One of the solution could be to create a proper web dashboard instead of rudimentary tkinter one we made.

Sure. If you really wanna try it:
In main.py,
Write a function:

`def next():
       os.system('python Auth.py')`
And in main.py:
Replace line 86:

`c=Button(Home1, text="Authenticate yourself", command=quit,bd=20, bg="black", fg="red", font=('times new roman', 20),relief=RIDGE).pack()`
with

`c=Button(Home1, text="Authenticate yourself", command=next, bd=20, bg="black", fg="red", font=('times new roman', 20),relief=RIDGE).pack()`

You can do it this way, though its is not recommended as doing so may slow down the process as the modules are being imported for Auth.py in the meantime.

**Comment by haithamRD** [comment]
thnx sir , have you a report about this application that u explain all features in this project please sir

**Comment by haithamRD** [comment]
hey sir , when i ran Auth.py  i have an error 
'None type' object is not subscriptable

**Comment by rishabh-karmakar** [comment]
For the report the readme.md may suffice, you can copy from there.

For the error, try downgrading the numpy version to one I mentioned in testing.txt?

`pip install numpy == 1.16.1`
